In [1]:
import random
import pandas as pd

In [ ]:
# Load the CSV file containing US inflation rates
df = pd.read_csv("./data/raw/US_inflation_rates.csv")
df["date"] = df["date"].str.slice(0,4)
df[:25]

    date  value
0   1947  21.48
1   1947  21.62
2   1947  22.00
3   1947  22.00
4   1947  21.95
5   1947  22.08
6   1947  22.23
7   1947  22.40
8   1947  22.84
9   1947  22.91
10  1947  23.06
11  1947  23.41
12  1948  23.68
13  1948  23.67
14  1948  23.50
15  1948  23.82
16  1948  24.01
17  1948  24.15
18  1948  24.40
19  1948  24.43
20  1948  24.36
21  1948  24.31
22  1948  24.16
23  1948  24.05
24  1949  24.01

In [ ]:
# Group by year and calculate the mean inflation rate for each year
df_yearly = df.groupby("date").mean().reset_index()
df_yearly.head()

   date      value
0  1947  22.331667
1  1948  24.045000
2  1949  23.809167
3  1950  24.062500
4  1951  25.973333

In [4]:
#check if missing years
df_yearly["date"].tolist() != list(str(x) for x in range(1947, 2026))

False

In [ ]:
# Add a column indicating whether each year was a recession year with different formats
recession_years = [1949, 1953, 1957, 1960, 1970, 1974, 1980, 1981, 1990, 2001, 2008, 2009, 2020]

positive_formats = ["Yes", "True", "TRUE", "1", 1, True]
negative_formats = ["No", "False", "FALSE", "0", 0, False]

def get_recession_status_random(year):
    if year in recession_years:
        return random.choice(positive_formats)
    else:
        return random.choice(negative_formats)
    
df_yearly['Is_Recession'] = df_yearly['date'].astype(str).str[:4].astype(int).apply(get_recession_status_random)
df_yearly[:10]

   date      value Is_Recession
0  1947  22.331667           No
1  1948  24.045000        False
2  1949  23.809167         TRUE
3  1950  24.062500           No
4  1951  25.973333        FALSE
5  1952  26.566667        False
6  1953  26.768333         TRUE
7  1954  26.865000            0
8  1955  26.795833        False
9  1956  27.190833        False

In [6]:
df_yearly.to_csv("./data/ready/US_inflation_rates_ready.csv", index=False)