# Assignment 1

In [75]:
import pandas as pd

df = pd.read_excel("./Teams_R3dw4rd_/data_analysis_raw.xlsx")
df.head()

,Category,Supplier,Brand,Year,Month,Profit (Month)
0,Treadmill,Peak Performance Gear,Apex Athletics,2018,1.0,13318
1,Treadmill,Peak Performance Gear,Apex Athletics,2018,2.0,12921
2,Treadmill,Peak Performance Gear,Apex Athletics,2018,3.0,13752
3,Treadmill,Peak Performance Gear,Apex Athletics,2018,4.0,13355
4,Treadmill,Peak Performance Gear,Apex Athletics,2018,5.0,12130

In [17]:
df.dtypes

Category           object
Supplier           object
Brand              object
Year                int64
Month             float64
Profit (Month)      int64
dtype: object

In [15]:
df.isnull().sum()

Category          1
Supplier          1
Brand             0
Year              0
Month             1
Profit (Month)    0
dtype: int64

In [46]:
# Region is not available, so i will calculate revenue of each supplier

df_revenue = df.drop(labels=["Year", "Month"], axis=1).groupby(by="Supplier",dropna=True).sum(numeric_only=True).rename(columns={"Profit (Month)":"Total Profit"}).reset_index()
df_revenue.head()

                     Supplier  Total Profit
0  Iron Stength Equipment Co.       4815635
1       Peak Performance Gear       5776791
2        Titan Fitness Supply       4826265

In [58]:
df_top3 = df.drop(labels=["Year", "Month","Supplier"], axis=1).groupby(by=["Category","Brand"],dropna=True).sum(numeric_only=True).rename(columns={"Profit (Month)":"Profit"}).sort_values(by="Profit").reset_index()
df_top3[:3]

         Category               Brand  Profit
0       Treadmill      Apex Athletics  947312
1  Rowing Machine  Ironclad Athletics  949192
2         Airbike         Steel Power  949326

In [73]:
df_monthly_profit = df.drop(labels=["Supplier", "Category", "Brand"], axis=1).groupby(by=["Year", "Month"]).sum(numeric_only=True).sort_values(by=["Year","Month"]).rename(columns={"Profit (Month)":"Profit"}).reset_index()
df_monthly_profit["Growth %"] = df_monthly_profit["Profit"].pct_change()*100
df_monthly_profit

    Year  Month  Profit  Growth %
0   2018    1.0  203207       NaN
1   2018    2.0  203996  0.388274
2   2018    3.0  194351 -4.728034
3   2018    4.0  209882  7.991212
4   2018    5.0  203784 -2.905442
..   ...    ...     ...       ...
72  2024    1.0  205590  1.895265
73  2024    2.0  195210 -5.048884
74  2024    3.0  203569  4.282055
75  2024    4.0  197416 -3.022562
76  2024    5.0  196749 -0.337865

[77 rows x 4 columns]

In [77]:
df_monthly_profit.to_excel("temp.xlsx", index=False)